### ISSUE TITLE
Propuesta de modelos a ajustar

### ISSUE THREAD

**Issue by sancas96** [prope-2020-gh-classroom/practica-final-por-equipos-verano-2020-itam-jreyesgar93#11]
- Proponer un modelo a ajustar

**Comment by sancas96** [comment]
Para los modelos se puede intentar encontrar un polinomio o función que nos ayude en la estimación de ventas

**Comment by jreyesgar93** [comment]
Es posible llamar a mi código para que trabajar con la base de datos ya limpia. si escribes <from data_cleaning * > se corre el código y tendras todas las variables, incuida el dataframe ya limpio (se llama df). Eliminamos más datos que solo año, así quue puede haber un pequeño cambio.

**Comment by jreyesgar93** [comment]
cierro issue.
