### ISSUE TITLE
Reporte de práctica final

### ISSUE THREAD

**Issue by sancas96** [prope-2020-gh-classroom/practica-final-por-equipos-verano-2020-itam-jreyesgar93#12]

**Comment by jreyesgar93** [comment]
trabajar sobre <practica_final_equipo_5.ipynb>

**Comment by sancas96** [comment]
El análisis exploratorio se agregó a la fase de modelos y al reporte final.

**Comment by sancas96** [comment]
se cierra el issue para completar el milestone
